config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :appointments,          only: [:create, :edit, :destroy, :update]
  resources :user_comments,          only: [:create, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  has_many :user_comments
  default_scope -> { order(appt_time: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true
  validates :appt_time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :user_comments
  before_save { name.downcase! }
  validates :name,  presence: true, length: { maximum: 50, minimum: 1 }, 
             uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
end

app/models/user_comment.rb
class UserComment < ApplicationRecord
  belongs_to :user
  belongs_to :appointment
  default_scope -> { order(:created_at) }
  validates :user_id, presence: true
  validates :appointment_id, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :logged_in_user, only: [:create, :edit, :destroy, :update]
  before_action :correct_user,   only: [:edit, :destroy, :update]

  def create
    @appointment = current_user.appointments.build(appointment_params)
    if @appointment.save
      flash[:success] = "Appointment created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end
  
  def edit
    @appointment = Appointment.find(params[:id])
  end

  def destroy
    @appointment.destroy
    flash[:success] = "Appointment deleted"
    redirect_to request.referrer || root_url
  end
  
  def update
    @appointment.update_attributes(appointment_params)
    flash[:success] = "Appointment updated!"
    redirect_to request.referrer || root_url
  end
  
  private

    def appointment_params
      params.require(:appointment).permit(:title, :appt_time)
    end
    
    def correct_user
      @appointment = current_user.appointments.find_by(id: params[:id])
      redirect_to root_url if @appointment.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(name: params[:session][:name].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid name/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)                                                                                                                                                                                                   
    reset_session
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @appointment = current_user.appointments.build
    end
  end
  
  def help
  end
end

app/controllers/user_comments_controller.rb
class UserCommentsController < ApplicationController
  before_action :logged_in_user, only: [:create, :new]

  def create
    @user_comment = current_user.user_comments.build(user_comment_params)

    if @user_comment.save
      #current_user.user_comments << @user_comment
      flash[:success] = "Comment posted!"
      redirect_to new_user_comment_path
    else
      flash[:danger] = "Comment FAIL!"
      redirect_to new_user_comment_path
    end
  end
  
  def new
    @user_comment = UserComment.new
  end

  private

    def user_comment_params
      params.require(:user_comment).permit(:content, :appointment_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:destroy]
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def index
    @users = User.all
  end
  
  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.
      log_in @user
      flash[:success] = "Welcome to the Appointment Manager!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    # Before filters

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Appointment Manager"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
  def time_diff
    flash_messages = []
    unless current_user.nil?
      current_user.appointments.each do |appt|
        unless appt.appt_time.nil?
          diff = ((appt.appt_time - Time.now) / 1.minute ).round
          if diff < 60 && diff > 0
            flash_messages << "Appointment in " + diff.to_s + " minutes"
          end
        end
      end
    end
    flash_messages
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def current_user?(user)
    user.id == session[:user_id]
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_comments_helper.rb
module UserCommentsHelper
  def available_appts
    appts = []
    Appointment.all.each do |appt|
      appts << appt.id
    end
    appts
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/_appointment.html.erb
<li id="appointment-<%= appointment.id %>">
  <span class="user"><%= link_to appointment.user.name, appointment.user %></span>
  <span class="title">
    <%= appointment.title %>
  </span>
  <span class="appt_time">Appointment Number: <%= appointment.id %></span>
  <span class="appt_time"><%= appointment.appt_time %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(appointment.created_at) %> ago.
    <% if current_user?(appointment.user) %>
      <%= link_to "delete", appointment, method: :delete,
                                       data: { confirm: "You sure?" } %>
      <%= link_to "edit", edit_appointment_path(appointment) %>
    <% end %>
  </span>
  <% if appointment.user_comments.any? %>
    <div class="col-md-12">
      <h5>Comments</h5>
      <ol class="comments">
        <% appointment.user_comments.each do |user_comment| %>
          <li id="user_comment-<%= user_comment.id %>">
            <span class="user"><%= link_to user_comment.user.name, user_comment.user %></span>
            <span class="content"><%= user_comment.content %></span>
            <span class="timestamp">
              Posted <%= time_ago_in_words(user_comment.created_at) %> ago.
            </span>
          </li>
        <% end %>
      </ol>
    </div>
  <% end %>
</li>

app/views/appointments/edit.html.erb
<% provide(:title, "Edit appointment") %>
<h1>Update your Appointment</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@appointment) do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :appt_time %>
      <%= f.email_field :appt_time, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Never miss an appointment again!
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "appointment manager", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% if logged_in? %>
        <h3>current time: <%= Time.now %></h3>
        <h3>upcoming appointments: </h3>
        <% if time_diff.empty? %>
          <p>none</p>
        <% else %>
          <ul>
            <% time_diff.each do |appt| %>
              <li><%= appt %></li>
            <% end %>
          </ul>
        <% end %>
      <% end %>  
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_appointment_form.html.erb
<%= form_for(@appointment) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :title, placeholder: "Appointment title?" %>
    <%= f.text_area :appt_time, placeholder: "Appointment time?" %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="appointments">
    <%= render @feed_items %>
  </ol>
<% end %>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.appointments.count, "appointment") %></span>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Need Help?!</h1>
<p>
  Common Questions/Answers:
  Q- Why isn't it working?
  A- Turn it on!
  Or contact (805) 123-4567 for additional help.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="appointment_form">
        <%= render 'shared/appointment_form' %>
      </section>
    </aside
  </div>
<% else %>  
  <div class="center jumbotron">
    <h1>Welcome to the Appointment Manager!</h1>
  
    <h2>
      Manage your appointments!
    </h2>
  
  </div>
<% end %>

app/views/user_comments/new.html.erb
<%= form_for(@user_comment) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Write comment..." %>
    <%= f.label :appointment_id %>
    <%= f.select :appointment_id, options_for_select(available_appts) %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/users/_user_comments.html.erb
<% if appointment.user_comments.any? %>
    <div class="col-md-12">
      <h5>Comments</h5>
      <ol class="comments">
        <% appointment.user_comments.each do |user_comment| %>
          <li id="user_comment-<%= user_comment.id %>">
            <span class="user"><%= link_to user_comment.user.name, user_comment.user %></span>
            <span class="content"><%= user_comment.content %></span>
            <span class="timestamp">
              Posted <%= time_ago_in_words(user_comment.created_at) %> ago.
            </span>
          </li>
          <% end %>
      </ol>
    </div>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.appointments.any? %>
      <h3>Appointments (<%= @user.appointments.count %>)</h3>
      <ol class="appointments">
        <%= render @user.appointments %>
        <%= link_to "comment on an appointment!", new_user_comment_path %>
      </ol>
    <% end %>
  </div>
</div>